export const START_OPEN_WINDOW = 'system/START_OPEN_WINDOW';
export const START_CLOSE_WINDOW = 'system/START_CLOSE_WINDOW';
export const START_RESIZE_WINDOW = 'system/START_RESIZE_WINDOW';
export const START_MINIMIZE_WINDOW = 'system/START_MINIMIZE_WINDOW';
export const START_SELECT_WINDOW = 'system/START_SELECT_WINDOW';
